sudo: required
language: php
php:
 - 5.6
services:
  - docker

before_install:
 - ./before_install.sh

script:
- docker exec -t notejam_container bash -c "/usr/local/bin/php /var/www/html/vendor/bin/phpunit"

before_deploy: 
 - ./before_deploy.sh

deploy:
 - provider: s3
   access_key_id: $AWS_ACCESS_KEY_ID
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   bucket: "notejam"
   region: $AWS_DEFAULT_ZONE
   local_dir: build
   skip_cleanup: true
   on:
     branch: master
 - provider: codedeploy
   access_key_id: $AWS_ACCESS_KEY_ID
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   bucket: "notejam"
   key: build/bundle.zip
   application: testapp
   region: $AWS_DEFAULT_ZONE
   deployment_group: $DEPLOYMENT_GROUP 
   on:
     branch: master
