sudo: required
language: php
php:
 - 5.6
services:
  - docker

before_install:
 - cd laravel/notejam
 - composer install 
 - cd ../../
 - docker build -f docker/Dockerfile_apache -t notejam:latest .
 - docker run --name notejam_container -d -p 80:80 notejam:latest
 - docker ps -a

script:
- docker exec -t notejam_container bash -c "/usr/local/bin/php /var/www/html/vendor/bin/phpunit"

before_deploy: "mkdir build; docker save notejam:latest > build/notejam.tar"

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "notejam"
  region: us-east-2
  local_dir: build
