FROM php:5.6.35-apache-jessie
RUN apt-get update && apt-get install -y libmcrypt-dev
RUN docker-php-ext-install mcrypt pdo pdo_mysql
RUN a2enmod rewrite
#ENV APACHE_DOCUMENT_ROOT /var/www/html/public
#RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
#RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
COPY docker/apache-config.conf /etc/apache2/sites-enabled/000-default.conf
COPY laravel/notejam /var/www/html 
RUN chown -R www-data.www-data /var/www/html
